### ISSUE TITLE
No Longer Works in latest A-Frame Version

### ISSUE THREAD

**Issue by stevel4857** [tizzle/aframe-sprite-component#3] opened 2017-05-17 23:01 UTC
Although it works in 2D it no longer works in my nightly browser in VR. Seems to be some conflict or throws an error. Still works fine in 2D but that's not what I need. Wish I knew enough to rewrite this. I really need the functionality in A-Frame for a project I'm working on.

**Comment by tizzle** [comment] 2017-05-18 08:21
Hey @stevel4857,

i definetely see that there is something strange afoot. Can you give me some details about your configuration? What device do you use? What Operation System, what Browser? Thanks a lot for your help.

Cheers

**Comment by stevel4857** [comment] 2017-05-18 15:01
I am on Windows10 latest Firefox nightly using NVidia1080ti. I'm using a
frame 5.0 but I also use the master.js at times. I can't see what version I
have added though.

Steve Luiting
http://sluiting.weebly.com
P: 720.563.9377

**Comment by stevel4857** [comment] 2017-05-18 15:12
And thanks for the quick response. IThis is one of the best dev communities I've seen for quick response to questions. I honestly didn't expect one so quickly.

**Comment by tizzle** [comment] 2017-05-21 20:55
Hey @stevel4857,

i had a look on the source today and i'm not able to reproduce what you experienced. I have to setup an environment like yours to investigate further. As i'm on a mac machine, this might take some time though. I will get back to you with more questions soon.

Sorry for the bad news, i hope you are not under a tight deadline here.

Cheers

Till

**Comment by tizzle** [comment] 2017-05-21 21:16
I have some follow up questions:
What device are you on? Is it a surface tablet?
Can you send me the code that is not working?

Thanks so much.

Till

**Comment by stevel4857** [comment] 2017-05-22 03:16
I'm on a,Windows 10 machine using Firefox nightly and aframe 5.0.

**Comment by stevel4857** [comment] 2017-05-22 03:18
I'm on a desktop machine with a nvidea 1080 card. I took the hot tub code
and updated from aframe 3.0 to 5.

On May 21, 2017 9:16 PM, "Steve Luiting" <luiting57@gmail.com> wrote:

I'm on a,Windows 10 machine using Firefox nightly and aframe 5.0.

**Comment by micuat** [comment] 2020-05-19 13:59
closing as it's not been updated - please reopen if the issue still persists

**Closed as completed** 2020-05-19 14:00 UTC
