### ISSUE TITLE
not able to works well with aframe-click-drag-component

### ISSUE THREAD

**Issue by fuj1w4r4** [tizzle/aframe-sprite-component#4] opened 2018-07-12 16:59 UTC
it took me a while to get to know three js sprite, a component which is 2d always face to camera.
I tried this lib with aframe-click-drag-component, but seems not able to work well. after dragged, it moves away.

**Comment by micuat** [comment] 2020-05-19 14:01
closing as it's been 2 years - please reopen if the issue is still there, and when you do so an example code would be very helpful

**Closed as completed by micuat** 2020-05-19 14:01 UTC
